export const lemonadeBlankFill = () => {
  const lemonadeBlanks = [
    'Who Is wearing a black top',
    'Who Is wearing a white top',
    'Who Is blonde',
    'Who Is brunette',
    'Who Is ginger',
    'Who Has curly hair',
    'Who Has straight hair',
    'Who Has blue eyes',
    'Who Has brown eyes',
    'Who Has green eyes',
    'Who Has an iPhone',
    'Who Has an Android',
    'Who Is taller than 6ft',
    'Who Is shorter than 6ft',
    'Who Is playing for the first time',
    'Who Is a lady',
    'Who Is a guy',
    'Who Is wearing Nikes',
    'Who Is in a relationship with someone',
    'Who Is wearing white socks',
    'Who Is wearing black socks',
    'Who Is wearing multi-coloured socks',
    'Who Has spilt their drink playing this game',
    'Who Has slept with someone from the group',
    "Who Has a driver's license",
    "Who Doesn't have a driver's license",
    'Who Owns a car',
    'Who Speaks more than one language',
    'Who Has any tattoos',
    'Who Is pierced',
    'Who Is addicted to something',
    'Who Smokes',
    'Who Vapes',
    'Who Is the tallest player',
    'Who Is the shortest player',
    'Who Is a virgin (Expansion pack promotion)',
    'Who Has a pet',
    'Who Has drank instead of doing the challenge',
    'Who Has the least amount of alcohol',
    'Who Has the biggest boobs',
    'Who Has a beard or moustache',
    'Who Is wearing makeup',
    'Who Is wearing glasses',
    'Who Is guests of the house',
    'Who Is the party host/-s',
    'Who Is wearing jewellery',
    'Who Is mom of the house',
    'Who Is dad of the house',
    'Who Plays video games',
    'Who Has a Netflix account',
    'Who is Vegetarian',
    'Who is Vegan',
    'Who Is taking shots',
    'Who Is having a cocktail',
    'Who Has the letter A is in your first name',
    'Who Has the letter I is in your first name',
    'Who Is wearing jeans',
    'Who Is wearing joggers',
    'Who Is feeling tipsy',
    'Who Is abroad right now',
    'Who Is NOT in their home country right now',
    'Who Is religious',
    'Who Has Spotify Premium',
    'Who Has Youtube Premium',
    'Who Likes pineapple on pizza',
    'Who Is a morning person',
    'Who Believes in ghosts',
    'Who Thinks aliens exist',
    'Who Was born in the Winter',
    'Who Was born in the Spring',
    'Who Was born in the Summer',
    'Who Was born in Autumn',
    'Who Thinks hotdogs are sandwiches',
    'Who has or had the TikTok app on your phone',
    'Who Is a dog lover',
    'Who Is a cat lover',
    'Who Is a student',
    'Who Has a full-time job',
    'Who Has a part-time job',
    'Who Is self-employed',
    'Who Thinks that Cola and Pepsi taste the same',
    'Who Is younger than 20 y.o.',
    'Who Is 20 y.o. or older',
    'Who Is older than 22 y.o.',
    'Who Is able to play a musical instrument',
    'Who Lives in a flat',
    'Who Knows what they are doing with their life',
    'Who Are financially dependent on your parents',
    'Who Has been in trouble with the Police',
    'Who Has been kicked out of the club or bar',
    'Who Has lied to any of the players',
    'Who Has a drink that is less than 15% ALC',
    'Who Has a drink that is 15% ALC or stronger',
    'Who Has eaten something whilst playing the game',
    "Who Hasn't done a challenge",
    'Who Has borrowed money from any of the players',
  ];
  const randomWordIndex = Math.floor(Math.random() * lemonadeBlanks.length) + 0;
  const blank = lemonadeBlanks[randomWordIndex];
  return blank;
};

// export const lemonBlank = () => {
//   const lemonBlanks = [
//     `If you're wearing a black top`,
//     `If you're wearing a white top`,
//     `If you're blonde`,
//     `If you're brunette`,
//     `If you're ginger`,
//     `If you have curly hair`,
//     `If you have straight hair`,
//     `If you have blue eyes`,
//     `If you have brown eyes`,
//     `If you have green eyes`,
//     `If you have an iPhone`,
//     `If you have an Android`,
//     `If you're taller than 6ft`,
//     `If you're shorter than 6ft`,
//     `If this is the first time playing`,
//     `If you're a lady`,
//     `If you're a guy`,
//     `If you're wearing Nikes`,
//     `If you're in a relationship with someone`,
//     `If your socks are white`,
//     `If your socks are black`,
//     `If your socks are more than one color`,
//     `If you've spilt your drink playing this game`,
//     `If you've slept with someone from the group`,
//     `If you don't have a driver's license`,
//     `If you have a driver's license`,
//     `If you own a car`,
//     `If you speak more than one language`,
//     `If you have any tattoos`,
//     `If you're pierced`,
//     `If you're addicted to something`,
//     `Smokers`,
//     `Vapers`,
//     `The tallest player`,
//     `The shortest player`,
//     `If your socks are multicolour`,
//     `Virgins (Expansion pack promotion)`,
//     `If you have a pet`,
//     `If you spun the spinner`,
//     `If you rolled the dice instead of doing the dare`,
//     `The player who had the least amount of alcohol`,
//     `The girl with the biggest boobs`,
//     `If you have a beard or moustache`,
//     `If you're wearing makeup`,
//     `If you're wearing glasses`,
//     `Guests of the house`,
//     `Party host/-s`,
//     `If you're wearing jewellery`,
//     `Mom of the house`,
//     `Dad of the house`,
//     `If you play video games`,
//     `If you have a Netflix account`,
//     `Vegetarians`,
//     `Vegans`,
//     `If you're taking shots`,
//     `If you're having a cocktail`,
//     `If the letter A is in your first name`,
//     `If the letter I is in your first name`,
//     `If you're wearing jeans`,
//     `If you're wearing joggers`,
//     `If you're feeling tipsy`,
//     `If you're abroad right now`,
//     `If you're NOT in your home country right now`,
//     `If you're religious`,
//     `If you have Spotify Premium`,
//     `If you have Youtube Premium`,
//     `If you don't mind pineapple on pizza`,
//     `If you're a morning person`,
//     `If you believe in ghosts`,
//     `If you think aliens exist`,
//     `If you were born in the Winter`,
//     `If you were born in the Spring`,
//     `If you were born in the Summer`,
//     `If you were born in Autumn`,
//     `If you think hotdogs are sandwiches`,
//     `If you have/had the TikTok app on your phone`,
//     `Dog lover/-s`,
//     `Cat lover/-s`,
//     `If you're a student`,
//     `If you have a full-time job`,
//     `If you have a part-time job`,
//     `If you're self-employed`,
//     `If you think that Cola and Pepsi taste the same`,
//     `If you're younger than 20 y.o.`,
//     `If you're 20 y.o. or older`,
//     `If you're older than 22 y.o.`,
//     `If you're able to play a musical instrument`,
//     `If you live in a flat`,
//     `If you know what you're doing with your life`,
//     `If you are financially dependent on your parents`,
//     `If you have ever been in trouble with the Police`,
//     `If you have ever been kicked out of the club or bar`,
//     `If you have ever lied to any of the players`,
//     `If your drink is less than 15% ALC`,
//     `If your drink is 15% ALC or stronger`,
//     `If you ate something whilst playing the game`,
//     `If you haven't spun the spinner`,
//     `If you haven't rolled the dice yet`,
//     `If you ever borrowed money from any of the players`,
//   ];
//   const randomWordIndex = Math.floor(Math.random() * lemonBlanks.length) + 0;
//   const challenge = lemonBlanks[randomWordIndex];
//   return challenge;
// };
