export const lemonadeBlankData = [
  {
    id: 'leb1',
    cardColor: 'lemonadeScore',
    content: 'Who Is wearing a black top',
  },
  {
    id: 'leb2',
    cardColor: 'lemonadeScore',
    content: 'Who Is wearing a white top',
  },
  {id: 'leb3', cardColor: 'lemonadeScore', content: 'Who Is blonde'},
  {id: 'leb4', cardColor: 'lemonadeScore', content: 'Who Is brunette'},
  {id: 'leb5', cardColor: 'lemonadeScore', content: 'Who Is ginger'},
  {id: 'leb6', cardColor: 'lemonadeScore', content: 'Who Has curly hair'},
  {id: 'leb7', cardColor: 'lemonadeScore', content: 'Who Has straight hair'},
  {id: 'leb8', cardColor: 'lemonadeScore', content: 'Who Has blue eyes'},
  {id: 'leb9', cardColor: 'lemonadeScore', content: 'Who Has brown eyes'},
  {id: 'leb10', cardColor: 'lemonadeScore', content: 'Who Has green eyes'},
  {id: 'leb11', cardColor: 'lemonadeScore', content: 'Who Has an iPhone'},
  {id: 'leb12', cardColor: 'lemonadeScore', content: 'Who Has an Android'},
  {id: 'leb13', cardColor: 'lemonadeScore', content: 'Who Is taller than 6ft'},
  {id: 'leb14', cardColor: 'lemonadeScore', content: 'Who Is shorter than 6ft'},
  {
    id: 'leb15',
    cardColor: 'lemonadeScore',
    content: 'Who Is playing for the first time',
  },
  {id: 'leb16', cardColor: 'lemonadeScore', content: 'Who Is a woman'},
  {id: 'leb17', cardColor: 'lemonadeScore', content: 'Who Is a man'},
  {id: 'leb18', cardColor: 'lemonadeScore', content: 'Who Is wearing Nikes'},
  {
    id: 'leb19',
    cardColor: 'lemonadeScore',
    content: 'Who Is in a relationship with someone',
  },
  {
    id: 'leb20',
    cardColor: 'lemonadeScore',
    content: 'Who Is wearing white socks',
  },
  {
    id: 'leb21',
    cardColor: 'lemonadeScore',
    content: 'Who Is wearing black socks',
  },
  {
    id: 'leb22',
    cardColor: 'lemonadeScore',
    content: 'Who Is wearing multi-coloured socks',
  },
  {
    id: 'leb23',
    cardColor: 'lemonadeScore',
    content: 'Who Has spilled their drink this game',
  },
  {
    id: 'leb24',
    cardColor: 'lemonadeScore',
    content: 'Who Has slept with someone from the group',
  },
  {
    id: 'leb25',
    cardColor: 'lemonadeScore',
    content: "Who Has a driver's license",
  },
  {
    id: 'leb26',
    cardColor: 'lemonadeScore',
    content: "Who Doesn't have a driver's license",
  },
  {id: 'leb27', cardColor: 'lemonadeScore', content: 'Who Owns a car'},
  {
    id: 'leb28',
    cardColor: 'lemonadeScore',
    content: 'Who Speaks more than one language',
  },
  {id: 'leb29', cardColor: 'lemonadeScore', content: 'Who Has tattoos'},
  {id: 'leb30', cardColor: 'lemonadeScore', content: 'Who Is pierced'},
  {
    id: 'leb31',
    cardColor: 'lemonadeScore',
    content: 'Who Is addicted to something',
  },
  {id: 'leb32', cardColor: 'lemonadeScore', content: 'Who Smokes'},
  {id: 'leb33', cardColor: 'lemonadeScore', content: 'Who Vapes'},
  {
    id: 'leb34',
    cardColor: 'lemonadeScore',
    content: 'Who Is the tallest player',
  },
  {
    id: 'leb35',
    cardColor: 'lemonadeScore',
    content: 'Who Is the shortest player',
  },
  {id: 'leb38', cardColor: 'lemonadeScore', content: 'Who Has a pet'},
  {
    id: 'leb40',
    cardColor: 'lemonadeScore',
    content: 'Who Has drank instead of doing the challenge',
  },
  {
    id: 'leb41',
    cardColor: 'lemonadeScore',
    content: 'Who Has the least amount of alcohol',
  },
  {
    id: 'leb42',
    cardColor: 'lemonadeScore',
    content: 'Who Has the biggest boobs',
  },
  {
    id: 'leb43',
    cardColor: 'lemonadeScore',
    content: 'Who Has a beard or moustache',
  },
  {id: 'leb44', cardColor: 'lemonadeScore', content: 'Who Is wearing makeup'},
  {id: 'leb45', cardColor: 'lemonadeScore', content: 'Who Is wearing glasses'},
  {
    id: 'leb48',
    cardColor: 'lemonadeScore',
    content: 'Who Is wearing jewellery',
  },
  {id: 'leb51', cardColor: 'lemonadeScore', content: 'Who Plays video games'},
  {
    id: 'leb52',
    cardColor: 'lemonadeScore',
    content: 'Who Has a Netflix account',
  },
  {id: 'leb53', cardColor: 'lemonadeScore', content: 'Who is Vegetarian'},
  {id: 'leb54', cardColor: 'lemonadeScore', content: 'Who is Vegan'},
  {id: 'leb55', cardColor: 'lemonadeScore', content: 'Who Is taking shots'},
  {
    id: 'leb56',
    cardColor: 'lemonadeScore',
    content: 'Who Is having a cocktail',
  },
  {
    id: 'leb57',
    cardColor: 'lemonadeScore',
    content: 'Who Has the letter A is in your first name',
  },
  {
    id: 'leb58',
    cardColor: 'lemonadeScore',
    content: 'Who Has the letter I is in your first name',
  },
  {id: 'leb59', cardColor: 'lemonadeScore', content: 'Who Is wearing jeans'},
  {id: 'leb60', cardColor: 'lemonadeScore', content: 'Who Is wearing joggers'},
  {id: 'leb61', cardColor: 'lemonadeScore', content: 'Who Is feeling tipsy'},

  {
    id: 'leb63',
    cardColor: 'lemonadeScore',
    content: 'Who Is NOT in their home country right now',
  },
  {id: 'leb64', cardColor: 'lemonadeScore', content: 'Who Is religious'},
  {id: 'leb65', cardColor: 'lemonadeScore', content: 'Who Has Spotify Premium'},
  {id: 'leb66', cardColor: 'lemonadeScore', content: 'Who Has Youtube Premium'},
  {
    id: 'leb67',
    cardColor: 'lemonadeScore',
    content: 'Who Likes pineapple on pizza',
  },
  {id: 'leb68', cardColor: 'lemonadeScore', content: 'Who Is a morning person'},
  {id: 'leb69', cardColor: 'lemonadeScore', content: 'Who Believes in ghosts'},
  {id: 'leb70', cardColor: 'lemonadeScore', content: 'Who Thinks aliens exist'},
  {
    id: 'leb71',
    cardColor: 'lemonadeScore',
    content: 'Who Was born in the Winter',
  },
  {
    id: 'leb72',
    cardColor: 'lemonadeScore',
    content: 'Who Was born in the Spring',
  },
  {
    id: 'leb73',
    cardColor: 'lemonadeScore',
    content: 'Who Was born in the Summer',
  },
  {id: 'leb74', cardColor: 'lemonadeScore', content: 'Who Was born in Autumn'},
  {
    id: 'leb75',
    cardColor: 'lemonadeScore',
    content: 'Who Thinks hotdogs are sandwiches',
  },
  {
    id: 'leb76',
    cardColor: 'lemonadeScore',
    content: 'Who has or had the TikTok app on your phone',
  },
  {id: 'leb77', cardColor: 'lemonadeScore', content: 'Who Is a dog lover'},
  {id: 'leb78', cardColor: 'lemonadeScore', content: 'Who Is a cat lover'},
  {id: 'leb79', cardColor: 'lemonadeScore', content: 'Who Is a student'},
  {id: 'leb80', cardColor: 'lemonadeScore', content: 'Who Has a full-time job'},
  {id: 'leb81', cardColor: 'lemonadeScore', content: 'Who Has a part-time job'},
  {id: 'leb82', cardColor: 'lemonadeScore', content: 'Who Is self-employed'},
  {
    id: 'leb83',
    cardColor: 'lemonadeScore',
    content: 'Who Thinks that Cola and Pepsi taste the same',
  },
  {id: 'leb84', cardColor: 'lemonadeScore', content: 'Who Is younger than 20'},
  {
    id: 'leb87',
    cardColor: 'lemonadeScore',
    content: 'Who Is able to play a musical instrument',
  },
  {id: 'leb88', cardColor: 'lemonadeScore', content: 'Who Lives in a flat'},
  {
    id: 'leb91',
    cardColor: 'lemonadeScore',
    content: 'Who Has been in trouble with the Police',
  },
  {
    id: 'leb92',
    cardColor: 'lemonadeScore',
    content: 'Who Has been kicked out of the club or bar',
  },
  {
    id: 'leb93',
    cardColor: 'lemonadeScore',
    content: 'Who Has lied to any of the players',
  },
  {
    id: 'leb94',
    cardColor: 'lemonadeScore',
    content: 'Who Has a drink that is less than 15% ALC',
  },
  {
    id: 'leb95',
    cardColor: 'lemonadeScore',
    content: 'Who Has a drink that is 15% ALC or stronger',
  },
  {
    id: 'leb96',
    cardColor: 'lemonadeScore',
    content: 'Who Has eaten something whilst playing the game',
  },
];
