export const lemonadeBlankData = [
  'Who Is wearing a black top',
  'Who Is wearing a white top',
  'Who Is blonde',
  'Who Is brunette',
  'Who Is ginger',
  'Who Has curly hair',
  'Who Has straight hair',
  'Who Has blue eyes',
  'Who Has brown eyes',
  'Who Has green eyes',
  'Who Has an iPhone',
  'Who Has an Android',
  'Who Is taller than 6ft',
  'Who Is shorter than 6ft',
  'Who Is playing for the first time',
  'Who Is a lady',
  'Who Is a guy',
  'Who Is wearing Nikes',
  'Who Is in a relationship with someone',
  'Who Is wearing white socks',
  'Who Is wearing black socks',
  'Who Is wearing multi-coloured socks',
  'Who Has spilt their drink playing this game',
  'Who Has slept with someone from the group',
  "Who Has a driver's license",
  "Who Doesn't have a driver's license",
  'Who Owns a car',
  'Who Speaks more than one language',
  'Who Has any tattoos',
  'Who Is pierced',
  'Who Is addicted to something',
  'Who Smokes',
  'Who Vapes',
  'Who Is the tallest player',
  'Who Is the shortest player',
  'Who Is a virgin (Expansion pack promotion)',
  'Who Has a pet',
  'Who Has drank instead of doing the challenge',
  'Who Has the least amount of alcohol',
  'Who Has the biggest boobs',
  'Who Has a beard or moustache',
  'Who Is wearing makeup',
  'Who Is wearing glasses',
  'Who Is guests of the house',
  'Who Is the party host/-s',
  'Who Is wearing jewellery',
  'Who Is mom of the house',
  'Who Is dad of the house',
  'Who Plays video games',
  'Who Has a Netflix account',
  'Who is Vegetarian',
  'Who is Vegan',
  'Who Is taking shots',
  'Who Is having a cocktail',
  'Who Has the letter A is in your first name',
  'Who Has the letter I is in your first name',
  'Who Is wearing jeans',
  'Who Is wearing joggers',
  'Who Is feeling tipsy',
  'Who Is abroad right now',
  'Who Is NOT in their home country right now',
  'Who Is religious',
  'Who Has Spotify Premium',
  'Who Has Youtube Premium',
  'Who Likes pineapple on pizza',
  'Who Is a morning person',
  'Who Believes in ghosts',
  'Who Thinks aliens exist',
  'Who Was born in the Winter',
  'Who Was born in the Spring',
  'Who Was born in the Summer',
  'Who Was born in Autumn',
  'Who Thinks hotdogs are sandwiches',
  'Who has or had the TikTok app on your phone',
  'Who Is a dog lover',
  'Who Is a cat lover',
  'Who Is a student',
  'Who Has a full-time job',
  'Who Has a part-time job',
  'Who Is self-employed',
  'Who Thinks that Cola and Pepsi taste the same',
  'Who Is younger than 20 y.o.',
  'Who Is 20 y.o. or older',
  'Who Is older than 22 y.o.',
  'Who Is able to play a musical instrument',
  'Who Lives in a flat',
  'Who Knows what they are doing with their life',
  'Who Are financially dependent on your parents',
  'Who Has been in trouble with the Police',
  'Who Has been kicked out of the club or bar',
  'Who Has lied to any of the players',
  'Who Has a drink that is less than 15% ALC',
  'Who Has a drink that is 15% ALC or stronger',
  'Who Has eaten something whilst playing the game',
  "Who Hasn't done a challenge",
  'Who Has borrowed money from any of the players',
];
