export const lemonadeBlankData = [
  {
    id: 'leb1',
    cardColor: 'lemonadeScore',
    content: 'Who is wearing a black top',
  },
  {
    id: 'leb2',
    cardColor: 'lemonadeScore',
    content: 'Who is wearing a white top',
  },
  {id: 'leb3', cardColor: 'lemonadeScore', content: 'Who is blonde'},
  {id: 'leb4', cardColor: 'lemonadeScore', content: 'Who is brunette'},
  {id: 'leb5', cardColor: 'lemonadeScore', content: 'Who is ginger'},
  {id: 'leb6', cardColor: 'lemonadeScore', content: 'Who has curly hair'},
  {id: 'leb7', cardColor: 'lemonadeScore', content: 'Who has straight hair'},
  {id: 'leb8', cardColor: 'lemonadeScore', content: 'Who has blue eyes'},
  {id: 'leb9', cardColor: 'lemonadeScore', content: 'Who has brown eyes'},
  {id: 'leb10', cardColor: 'lemonadeScore', content: 'Who has green eyes'},
  {id: 'leb11', cardColor: 'lemonadeScore', content: 'Who has an iPhone'},
  {id: 'leb12', cardColor: 'lemonadeScore', content: 'Who has an Android'},
  {id: 'leb13', cardColor: 'lemonadeScore', content: 'Who is taller than 6ft'},
  {id: 'leb14', cardColor: 'lemonadeScore', content: 'Who is shorter than 6ft'},
  {
    id: 'leb15',
    cardColor: 'lemonadeScore',
    content: 'Who is playing for the first time',
  },
  {id: 'leb16', cardColor: 'lemonadeScore', content: 'Who is a woman'},
  {id: 'leb17', cardColor: 'lemonadeScore', content: 'Who is a man'},
  {id: 'leb18', cardColor: 'lemonadeScore', content: 'Who is wearing Nikes'},
  {
    id: 'leb19',
    cardColor: 'lemonadeScore',
    content: 'Who is in a relationship with someone',
  },
  {
    id: 'leb20',
    cardColor: 'lemonadeScore',
    content: 'Who is wearing white socks',
  },
  {
    id: 'leb21',
    cardColor: 'lemonadeScore',
    content: 'Who is wearing black socks',
  },
  {
    id: 'leb22',
    cardColor: 'lemonadeScore',
    content: 'Who is wearing multi-coloured socks',
  },
  {
    id: 'leb23',
    cardColor: 'lemonadeScore',
    content: 'Who has spilled their drink this game',
  },
  {
    id: 'leb24',
    cardColor: 'lemonadeScore',
    content: 'Who has slept with someone from the group',
  },
  {
    id: 'leb25',
    cardColor: 'lemonadeScore',
    content: "Who has a driver's license",
  },
  {
    id: 'leb26',
    cardColor: 'lemonadeScore',
    content: "Who doesn't have a driver's license",
  },
  {id: 'leb27', cardColor: 'lemonadeScore', content: 'Who owns a car'},
  {
    id: 'leb28',
    cardColor: 'lemonadeScore',
    content: 'Who speaks more than one language',
  },
  {id: 'leb29', cardColor: 'lemonadeScore', content: 'Who has tattoos'},
  {id: 'leb30', cardColor: 'lemonadeScore', content: 'Who has piercings'},
  {
    id: 'leb31',
    cardColor: 'lemonadeScore',
    content: 'Who is addicted to something',
  },
  {id: 'leb32', cardColor: 'lemonadeScore', content: 'Who smokes'},
  {id: 'leb33', cardColor: 'lemonadeScore', content: 'Who vapes'},
  {
    id: 'leb34',
    cardColor: 'lemonadeScore',
    content: 'Who is the tallest player',
  },
  {
    id: 'leb35',
    cardColor: 'lemonadeScore',
    content: 'Who is the shortest player',
  },
  {id: 'leb38', cardColor: 'lemonadeScore', content: 'Who has a pet'},
  {
    id: 'leb40',
    cardColor: 'lemonadeScore',
    content: 'Who has drank instead of doing the challenge',
  },
  {
    id: 'leb41',
    cardColor: 'lemonadeScore',
    content: 'Who has the least amount of alcohol',
  },
  {
    id: 'leb42',
    cardColor: 'lemonadeScore',
    content: 'Who has the biggest boobs',
  },
  {
    id: 'leb43',
    cardColor: 'lemonadeScore',
    content: 'Who has a beard or moustache',
  },
  {id: 'leb44', cardColor: 'lemonadeScore', content: 'Who is wearing make-up'},
  {id: 'leb45', cardColor: 'lemonadeScore', content: 'Who is wearing glasses'},
  {
    id: 'leb48',
    cardColor: 'lemonadeScore',
    content: 'Who is wearing jewellery',
  },
  {id: 'leb51', cardColor: 'lemonadeScore', content: 'Who plays video games'},
  {
    id: 'leb52',
    cardColor: 'lemonadeScore',
    content: 'Who has a Netflix account',
  },
  {id: 'leb53', cardColor: 'lemonadeScore', content: 'Who is Vegetarian'},
  {id: 'leb54', cardColor: 'lemonadeScore', content: 'Who is Vegan'},
  {id: 'leb55', cardColor: 'lemonadeScore', content: 'Who Is taking shots'},
  {
    id: 'leb56',
    cardColor: 'lemonadeScore',
    content: 'Who is having a cocktail',
  },
  {
    id: 'leb57',
    cardColor: 'lemonadeScore',
    content: 'Who has the letter A is in your first name',
  },
  {
    id: 'leb58',
    cardColor: 'lemonadeScore',
    content: 'Who has the letter I is in your first name',
  },
  {id: 'leb59', cardColor: 'lemonadeScore', content: 'Who is wearing jeans'},
  {id: 'leb60', cardColor: 'lemonadeScore', content: 'Who is wearing joggers'},
  {id: 'leb61', cardColor: 'lemonadeScore', content: 'Who is feeling tipsy'},

  {
    id: 'leb63',
    cardColor: 'lemonadeScore',
    content: 'Who is NOT in their home country right now',
  },
  {id: 'leb64', cardColor: 'lemonadeScore', content: 'Who is religious'},
  {id: 'leb65', cardColor: 'lemonadeScore', content: 'Who has Spotify Premium'},
  {id: 'leb66', cardColor: 'lemonadeScore', content: 'Who has Youtube Premium'},
  {
    id: 'leb67',
    cardColor: 'lemonadeScore',
    content: 'Who likes pineapple on pizza',
  },
  {id: 'leb68', cardColor: 'lemonadeScore', content: 'Who is a morning person'},
  {id: 'leb69', cardColor: 'lemonadeScore', content: 'Who believes in ghosts'},
  {id: 'leb70', cardColor: 'lemonadeScore', content: 'Who thinks aliens exist'},
  {
    id: 'leb71',
    cardColor: 'lemonadeScore',
    content: 'Who was born in the Winter',
  },
  {
    id: 'leb72',
    cardColor: 'lemonadeScore',
    content: 'Who was born in the Spring',
  },
  {
    id: 'leb73',
    cardColor: 'lemonadeScore',
    content: 'Who was born in the Summer',
  },
  {id: 'leb74', cardColor: 'lemonadeScore', content: 'Who was born in Autumn'},
  {
    id: 'leb75',
    cardColor: 'lemonadeScore',
    content: 'Who thinks hotdogs are sandwiches',
  },
  {
    id: 'leb76',
    cardColor: 'lemonadeScore',
    content: 'Who has or had the TikTok app on your phone',
  },
  {id: 'leb77', cardColor: 'lemonadeScore', content: 'Who is a dog lover'},
  {id: 'leb78', cardColor: 'lemonadeScore', content: 'Who is a cat lover'},
  {id: 'leb79', cardColor: 'lemonadeScore', content: 'Who is a student'},
  {id: 'leb80', cardColor: 'lemonadeScore', content: 'Who has a full-time job'},
  {id: 'leb81', cardColor: 'lemonadeScore', content: 'Who has a part-time job'},
  {id: 'leb82', cardColor: 'lemonadeScore', content: 'Who is self-employed'},
  {
    id: 'leb83',
    cardColor: 'lemonadeScore',
    content: 'Who thinks that Cola and Pepsi taste the same',
  },
  {id: 'leb84', cardColor: 'lemonadeScore', content: 'Who is younger than 20'},
  {
    id: 'leb87',
    cardColor: 'lemonadeScore',
    content: 'Who is able to play a musical instrument',
  },
  {id: 'leb88', cardColor: 'lemonadeScore', content: 'Who lives in a flat'},
  {
    id: 'leb91',
    cardColor: 'lemonadeScore',
    content: 'Who has been in trouble with the Police',
  },
  {
    id: 'leb92',
    cardColor: 'lemonadeScore',
    content: 'Who has been kicked out of the club or bar',
  },
  {
    id: 'leb93',
    cardColor: 'lemonadeScore',
    content: 'Who has lied to any of the players',
  },
  {
    id: 'leb94',
    cardColor: 'lemonadeScore',
    content: 'Who has a drink that is less than 15% ALC',
  },
  {
    id: 'leb95',
    cardColor: 'lemonadeScore',
    content: 'Who has a drink that is 15% ALC or stronger',
  },
  {
    id: 'leb96',
    cardColor: 'lemonadeScore',
    content: 'Who has eaten something whilst playing the game',
  },
];
