export const martiniBlankData = [
  {
    id: 'mab1',
    cardColor: 'martiniScore',
    content: `Roast other players for 30 seconds`,
    timer: 30,
  },
  {
    id: 'mab2',
    cardColor: 'martiniScore',
    content: `Curse every 3 seconds`,
    timer: 3,
  },
  {
    id: 'mab3',
    cardColor: 'martiniScore',
    content: `Offer everyone shots for 10 seconds`,
    timer: 10,
  },
  {
    id: 'mab4',
    cardColor: 'martiniScore',
    content: `Giggle for 5 seconds`,
    timer: 5,
  },
  {
    id: 'mab5',
    cardColor: 'martiniScore',
    content: `Whistle for 10 seconds`,
    timer: 10,
  },
  {
    id: 'mab6',
    cardColor: 'martiniScore',
    content: `Whisper for 10 seconds`,
    timer: 10,
  },
  {
    id: 'mab7',
    cardColor: 'martiniScore',
    content: `Moan for 10 seconds`,
    timer: 10,
  },
  {
    id: 'mab8',
    cardColor: 'martiniScore',
    content: `Sing for 30 seconds`,
    timer: 30,
  },
  {
    id: 'mab9',
    cardColor: 'martiniScore',
    content: `Rap for 30 seconds`,
    timer: 30,
  },
  {
    id: 'mab10',
    cardColor: 'martiniScore',
    content: `Scream for 5 seconds`,
    timer: 5,
  },
  {
    id: 'mab11',
    cardColor: 'martiniScore',
    content: `Improvise a presentation for 1 minute`,
    timer: 60,
  },
  {
    id: 'mab12',
    cardColor: 'martiniScore',
    content: `Get roasted for 30 seconds`,
    timer: 30,
  },
  {
    id: 'mab13',
    cardColor: 'martiniScore',
    content: `Make fart sounds for 10 seconds`,
    timer: 10,
  },
  {
    id: 'mab14',
    cardColor: 'martiniScore',
    content: `Make chicken sounds for 10 seconds`,
    timer: 10,
  },
  {
    id: 'mab15',
    cardColor: 'martiniScore',
    content: `Bark like a dog for 10 seconds`,
    timer: 10,
  },
  {
    id: 'mab16',
    cardColor: 'martiniScore',
    content: `Yell at everyone for 10 seconds`,
    timer: 10,
  },
  {
    id: 'mab17',
    cardColor: 'martiniScore',
    content: `Meow like a cat for 10 seconds`,
    timer: 10,
  },
];
