export const martiniBlankData = [
  // {
  //   id: 'mab4',
  //   cardColor: 'martiniScore',
  //   content: `bare your teeth`,
  //   timer: 30,
  // },
  {
    id: 'mab5',
    cardColor: 'martiniScore',
    content: `whistle a quick melody`,
    timer: 3,
  },
  {
    id: 'mab7',
    cardColor: 'martiniScore',
    content: `moan`,
    timer: 10,
  },
  {
    id: 'mab8',
    cardColor: 'martiniScore',
    content: `sing your favourite song`,
    timer: 5,
  },
  {
    id: 'mab9',
    cardColor: 'martiniScore',
    content: `mumble rap`,
    timer: 10,
  },
  {
    id: 'mab10',
    cardColor: 'martiniScore',
    content: `scream`,
    timer: 10,
  },
  {
    id: 'mab11',
    cardColor: 'martiniScore',
    content: `make fart sounds`,
    timer: 10,
  },
  {
    id: 'mab12',
    cardColor: 'martiniScore',
    content: `make chicken sounds`,
    timer: 30,
  },
  {
    id: 'mab13',
    cardColor: 'martiniScore',
    content: `bark like a dog`,
    timer: 30,
  },
  {
    id: 'mab14',
    cardColor: 'martiniScore',
    content: `yell at your phone`,
    timer: 5,
  },
  {
    id: 'mab15',
    cardColor: 'martiniScore',
    content: `meow like a cat`,
    timer: 60,
  },
  {
    id: 'mab16',
    cardColor: 'martiniScore',
    content: `breathe like a dog with your tongue out`,
    timer: 30,
  },
  {
    id: 'mab19',
    cardColor: 'martiniScore',
    content: `yodel from the heart`,
    timer: 10,
  },
  {
    id: 'mab20',
    cardColor: 'martiniScore',
    content: `cry tears of joy`,
    timer: 10,
  },
  {
    id: 'mab21',
    cardColor: 'martiniScore',
    content: `trash talk`,
    timer: 10,
  },
  {
    id: 'mab22',
    cardColor: 'martiniScore',
    content: `groan like you've stepped on a lego`,
    timer: 10,
  },
  {
    id: 'mab25',
    cardColor: 'martiniScore',
    content: `argue with your belly`,
    timer: 10,
  },
  {
    id: 'mab27',
    cardColor: 'martiniScore',
    content: `sing a verse of "Jingle Bells"`,
    timer: 10,
  },
  {
    id: 'mab29',
    cardColor: 'martiniScore',
    content: `play an imaginary trumpet`,
    timer: 10,
  },
  {
    id: 'mab37',
    cardColor: 'martiniScore',
    content: `pray like the world is about to end`,
    timer: 10,
  },
  // {
  //   id: 'mab45',
  //   cardColor: 'martiniScore',
  //   content: `preach like you're the shit`,
  //   timer: 10,
  // },
  // {
  //   id: 'mab47',
  //   cardColor: 'martiniScore',
  //   content: `apologise for being so humble`,
  //   timer: 10,
  // },
  {
    id: 'mab48',
    cardColor: 'martiniScore',
    content: 'reveal something embarassing about yourself',
    timer: 10,
  },
  // {
  //   id: 'mab49',
  //   cardColor: 'martiniScore',
  //   content: `convince everyone oxygen is bad for you`,
  //   timer: 10,
  // },
  {
    id: 'mab50',
    cardColor: 'martiniScore',
    content: `express your love for croissants in a french accent`,
    timer: 10,
  },
  {
    id: 'mab52',
    cardColor: 'martiniScore',
    content: 'hiss like an aggressive goose',
    timer: 10,
  },
  // {
  //   id: 'mab53',
  //   cardColor: 'martiniScore',
  //   content: `describe how much you love yourself`,
  //   timer: 10,
  // },
  {
    id: 'mab55',
    cardColor: 'martiniScore',
    content: `describe how you feel in an italian accent`,
    timer: 10,
  },
  {
    id: 'mab56',
    cardColor: 'martiniScore',
    content: `flirt with a wall`,
    timer: 10,
  },
  {
    id: 'mab57',
    cardColor: 'martiniScore',
    content: 'croak like a frog',
    timer: 10,
  },
  {
    id: 'mab58',
    cardColor: 'martiniScore',
    content: `sweet-talk to your drink`,
    timer: 10,
  },
  {
    id: 'mab59',
    cardColor: 'martiniScore',
    content: `brag about your sick lifestyle`,
    timer: 10,
  },
  {
    id: 'mab65',
    cardColor: 'martiniScore',
    content: `perform a sweet serenade`,
    timer: 10,
  },
  // {
  //   id: 'mab67',
  //   cardColor: 'martiniScore',
  //   content: `make a fuss of the Tooth Fairy scam`,
  //   timer: 10,
  // },
  // {
  //   id: 'mab68',
  //   cardColor: 'martiniScore',
  //   content: `raise a witty toast`,
  //   timer: 10,
  //},
  {
    id: 'mab69',
    cardColor: 'martiniScore',
    content: 'howl like you are a werewolf',
    timer: 10,
  },
  // {
  //   id: 'mab70',
  //   cardColor: 'martiniScore',
  //   content: `give your best excuse to leave early`,
  //   timer: 10,
  // },
  // {
  //   id: 'mab72',
  //   cardColor: 'martiniScore',
  //   content: `give out a backhanded compliment`,
  //   timer: 10,
  // },
  {
    id: 'mab75',
    cardColor: 'martiniScore',
    content: `tell a dad joke`,
    timer: 10,
  },
  // {
  //   id: 'mab77',
  //   cardColor: 'martiniScore',
  //   content: `comment everyone's choice of drink`,
  //   timer: 10,
  // },
  // {
  //   id: 'mab78',
  //   cardColor: 'martiniScore',
  //   content: `mention how smart you are`,
  //   timer: 10,
  // },
  // {
  //   id: 'mab79',
  //   cardColor: 'martiniScore',
  //   content: `bat around your daddy issues`,
  //   timer: 10,
  // },
  {
    id: 'mab80',
    cardColor: 'martiniScore',
    content: `verbally attack a frying pan`,
    timer: 10,
  },
  {
    id: 'mab85',
    cardColor: 'martiniScore',
    content: `beg for mercy`,
    timer: 10,
  },
  // {
  //   id: 'mab86',
  //   cardColor: 'martiniScore',
  //   content: `report on the current state of the party`,
  //   timer: 10,
  // },
  {
    id: 'mab90',
    cardColor: 'martiniScore',
    content: 'convince everyone you are a flat earther',
    timer: 10,
  },
  {
    id: 'mab92',
    cardColor: 'martiniScore',
    content: `aggressively describe how to make toast`,
    timer: 10,
  },
  {
    id: 'mab97',
    cardColor: 'martiniScore',
    content: `rehearse your best pick-up line`,
    timer: 10,
  },
  {
    id: 'mab101',
    cardColor: 'martiniScore',
    content: 'make guitar noises',
    timer: 10,
  },
];
