export const whiskeyBlankData = [
  {
    id: 'whb1',
    cardColor: 'whiskeyScore',
    content: 'do 10 push-ups',
    timer: false,
  },
  {
    id: 'whb2',
    cardColor: 'whiskeyScore',
    content: 'squat like a slav',
    timer: 10,
  },
  // {
  //   id: 'whb3',
  //   cardColor: 'whiskeyScore',
  //   content: 'take a whiff of your armpits',
  //   timer: false,
  // },
  // {
  //   id: 'whb4',
  //   cardColor: 'whiskeyScore',
  //   content: 'get kicked in the ass',
  //   timer: false,
  // },
  // {
  //   id: 'whb5',
  //   cardColor: 'whiskeyScore',
  //   content: 'swing your hips back and forth',
  //   timer: 10,
  // },
  // {
  //   id: 'whb6',
  //   cardColor: 'whiskeyScore',
  //   content: 'hug someone',
  //   timer: false,
  // },
  // {
  //   id: 'whb7',
  //   cardColor: 'whiskeyScore',
  //   content: 'jog like your crotch is on fire',
  //   timer: 20,
  // },
  // {
  //   id: 'whb8',
  //   cardColor: 'whiskeyScore',
  //   content: 'move like Michael Jackson',
  //   timer: 20,
  // },
  // {
  //   id: 'whb9',
  //   cardColor: 'whiskeyScore',
  //   content: 'strike a funny pose',
  //   timer: false,
  // },
  // {
  //   id: 'whb15',
  //   cardColor: 'whiskeyScore',
  //   content: 'pretend to drown in a pool',
  //   timer: 10,
  // },
  // {
  //   id: 'whb16',
  //   cardColor: 'whiskeyScore',
  //   content: 'crawl',
  //   timer: 10,
  // },
  // {
  //   id: 'whb17',
  //   cardColor: 'whiskeyScore',
  //   content: 'clap',
  //   timer: 10,
  // },
  // {
  //   id: 'whb18',
  //   cardColor: 'whiskeyScore',
  //   content: 'jump',
  //   timer: 10,
  // },
  // {
  //   id: 'whb19',
  //   cardColor: 'whiskeyScore',
  //   content: 'get spanked',
  //   timer: false,
  // },
  // {
  //   id: 'whb20',
  //   cardColor: 'whiskeyScore',
  //   content: 'do squats',
  //   timer: false,
  // },
  // {
  //   id: 'whb21',
  //   cardColor: 'whiskeyScore',
  //   content: 'dance',
  //   timer: 20,
  // },
  // {
  //   id: 'whb22',
  //   cardColor: 'whiskeyScore',
  //   content: 'jump on one leg',
  //   timer: false,
  // },
  // // {
  // //   id: 'whb23',
  // //   content: 'Melt an ice cube without using your arms',
  // //   timer: false,
  // // },
  // {
  //   id: 'whb24',
  //   cardColor: 'whiskeyScore',
  //   content: 'shake your head',
  //   timer: false,
  // },
  // {
  //   id: 'whb25',
  //   cardColor: 'whiskeyScore',
  //   content: 'get slapped',
  //   timer: false,
  // },
  // {
  //   id: 'whb26',
  //   cardColor: 'whiskeyScore',
  //   content: 'get pinched',
  //   timer: false,
  // },
  // {
  //   id: 'whb27',
  //   cardColor: 'whiskeyScore',
  //   content: 'get tickled',
  //   timer: 10,
  // },
  // {
  //   id: 'whb28',
  //   cardColor: 'whiskeyScore',
  //   content: 'lick your arms like a cat',
  //   timer: 10,
  // },
  // {
  //   id: 'whb29',
  //   cardColor: 'whiskeyScore',
  //   content: 'get poked',
  //   timer: false,
  // },
  // {
  //   id: 'whb30',
  //   cardColor: 'whiskeyScore',
  //   content: 'peck someone like a bird',
  //   timer: false,
  // },
  // {
  //   id: 'whb31',
  //   cardColor: 'whiskeyScore',
  //   content: 'twerk',
  //   timer: false,
  // },
  // {
  //   id: 'whb36',
  //   cardColor: 'whiskeyScore',
  //   content: 'stoke your hair',
  //   timer: false,
  // },
  // {
  //   id: 'whb38',
  //   cardColor: 'whiskeyScore',
  //   content: 'moonwalk',
  //   timer: false,
  // },
  // {
  //   id: 'whb39',
  //   cardColor: 'whiskeyScore',
  //   content: 'break dance',
  //   timer: false,
  // },
  // {
  //   id: 'whb40',
  //   cardColor: 'whiskeyScore',
  //   content: 'pretend to ride on a horse',
  //   timer: false,
  // },
  // {
  //   id: 'whb42',
  //   cardColor: 'whiskeyScore',
  //   content: 'jump-jack',
  //   timer: false,
  // },
  // {
  //   id: 'whb45',
  //   cardColor: 'whiskeyScore',
  //   content: 'rave like a party animal',
  //   timer: false,
  // },
  // {
  //   id: 'whb51',
  //   cardColor: 'whiskeyScore',
  //   content: 'pray',
  //   timer: false,
  // },
  // {
  //   id: 'whb54',
  //   cardColor: 'whiskeyScore',
  //   content: 'flop like a fish',
  //   timer: false,
  // },
  // {
  //   id: 'whb56',
  //   cardColor: 'whiskeyScore',
  //   content: 'robo-dance',
  //   timer: false,
  // },
  // {
  //   id: 'whb58',
  //   cardColor: 'whiskeyScore',
  //   content: 'lick your thumb',
  //   timer: false,
  // },
  // {
  //   id: 'whb60',
  //   cardColor: 'whiskeyScore',
  //   content: 'kneel',
  //   timer: false,
  // },
  // {
  //   id: 'whb62',
  //   cardColor: 'whiskeyScore',
  //   content: 'hop left to right',
  //   timer: false,
  // },
  // {
  //   id: 'whb64',
  //   cardColor: 'whiskeyScore',
  //   content: 'imitate one of the other players',
  //   timer: false,
  // },
  // {
  //   id: 'whb65',
  //   cardColor: 'whiskeyScore',
  //   content: 'fight a ghost',
  //   timer: false,
  // },
  // {
  //   id: 'whb67',
  //   cardColor: 'whiskeyScore',
  //   content: 'limp like a pimp',
  //   timer: false,
  // },
  // {
  //   id: 'whb68',
  //   cardColor: 'whiskeyScore',
  //   content: 'roll like a barrel',
  //   timer: false,
  // },
  // {
  //   id: 'whb70',
  //   cardColor: 'whiskeyScore',
  //   content: 'get a wedgie',
  //   timer: false,
  // },
  // {
  //   id: 'whb74',
  //   cardColor: 'whiskeyScore',
  //   content: 'drop dead',
  //   timer: false,
  // },
  // {
  //   id: 'whb76',
  //   cardColor: 'whiskeyScore',
  //   content: 'do a split',
  //   timer: false,
  // },
  // {
  //   id: 'whb77',
  //   cardColor: 'whiskeyScore',
  //   content: 'awkwardly wink',
  //   timer: false,
  // },
  // {
  //   id: 'whb82',
  //   cardColor: 'whiskeyScore',
  //   content: 'sumersault backwards',
  //   timer: false,
  // },
  // {
  //   id: 'whb87',
  //   cardColor: 'whiskeyScore',
  //   content: 'wrestle an imaginary bear',
  //   timer: false,
  // },
  // {
  //   id: 'whb88',
  //   cardColor: 'whiskeyScore',
  //   content: 'mime pulling on a rope',
  //   timer: false,
  // },
  // {
  //   id: 'whb89',
  //   cardColor: 'whiskeyScore',
  //   content: `cling to table's leg`,
  //   timer: false,
  // },
  // {
  //   id: 'whb90',
  //   cardColor: 'whiskeyScore',
  //   content: 'climb over an invisible wall',
  //   timer: false,
  // },
  // {
  //   id: 'whb92',
  //   cardColor: 'whiskeyScore',
  //   content: 'perform a karate chop',
  //   timer: false,
  // },
  // {
  //   id: 'whb94',
  //   cardColor: 'whiskeyScore',
  //   content: 'do the three-step waltz',
  //   timer: false,
  // },

  // {
  //   id: 'whb98',
  //   cardColor: 'whiskeyScore',
  //   content: 'tap dance',
  //   timer: false,
  // },
];
