export const lemonadeCardData = [
  {
    id: 'lec1',
    title: `Stinky Feet`,
    content_line_one: `take off your socks without using your hands and be the first to clap your bare feet.`,
    comment: `No hander.`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  // {
  //   id: 'lec2',
  //   title: `Paper Plane`,
  //   content_line_one: `make a paper plane and be the first to fly it into a wall across the room.`,
  //   comment: `Plane and simple.`,
  //   timer: false,
  //   cardColor: 'lemonadeScore',
  // },
  {
    id: 'lec3',
    title: `Poked & Soaked`,
    content_line_one: `hold a mouthful of water and poke eachother, last one to have water in their mouth wins.`,
    comment: `Just like a balloon`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec4',
    title: `Chair in Hell`,
    content_line_one: `wall sit until the knees give up, last person sitting wins.`,
    comment: `Oooh sit.`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec5',
    title: `Stuff on Stuff`,
    content_line_one: `get 5 different items and stack them up as quick as you can, first to stack all 5 wins.`,
    comment: `Choose them wisely`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  // {
  //   id: 'lec6',
  //   title: `Suck and Blow`,
  //   content_line_one: `stick a card to your lips and pass it around without dropping it.`,
  //   comment: `Don't let it fall!`,
  //   timer: false,
  //   cardColor: 'lemonadeScore',
  // },
  {
    id: 'lec7',
    title: `Plank on Fire`,
    content_line_one: `get into a plank position and hold it until your abs give out.`,
    comment: `My mind has gone plank`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec8',
    title: `Brain Fog`,
    content_line_one: `pick one random category and take turns naming things in that category, repeats or pauses eliminates players.`,
    comment: `Pause = Fail`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec9',
    title: `Sturdy Squat`,
    content_line_one: `balance one random item on your head and do as many squats as you can without dropping it, most squats wins.`,
    comment: `Until one jock remains.`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  // {
  //   id: 'lec10',
  //   title: `Tea Toe-el`,
  //   content_line_one: `stand in a circle and use your toes to pass a kitchen towel around without letting it touch the ground.`,
  //   comment: `Drop it and you're out!`,
  //   timer: false,
  //   cardColor: 'lemonadeScore',
  // },
  {
    id: 'lec11',
    title: 'Wipe out',
    content_line_one: `spin around 15 times and race to the nearest exit without falling or touching the walls.`,
    comment: `Merry go round`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec12',
    title: `Limbo`,
    content_line_one: `play limbo, falling eliminates you, lowest limbo wins.`,
    comment: `How low can you go?`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec13',
    title: `Last Breath`,
    content_line_one: `hold your breath for as long as you can.`,
    comment: `Plug that nose!`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  // {
  //   id: 'lec14',
  //   title: `YMCA`,
  //   content_line_one: `stand on one leg and do the "YMCA" dance.`,
  //   comment: ``,
  //   timer: false,
  //   cardColor: 'lemonadeScore',
  // },
  // {
  //   id: 'lec15',
  //   title: `Over the Top`,
  //   content_line_one: `top off a water glass without spilling (last to pour in water)`,
  //   comment: ``,
  //   timer: false,
  //   cardColor: 'lemonadeScore',
  // },
];
