export const lemonadeCardData = [
  {
    id: 'lec1',
    title: `Stinky Feet`,
    content_line_one: `take off your socks.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec2',
    title: `Peel Off`,
    content_line_one: `Lose one piece of clothing.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec3',
    title: `Paper Plane`,
    content_line_one: `make a paper plane and throw it across the room. If it flies well and hits the wall on the other side - you're safe. If not - you know what to do... DRINK!`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec4',
    title: `Off The Grid`,
    content_line_one: `switch off your phone for the rest of the game.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec5',
    title: `Bank Roll`,
    content_line_one: `tell everyone how much money you currently have in your bank account.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec6',
    title: `Lay Bare`,
    content_line_one: `let the player to your right look through your phone for 1 minute.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec7',
    title: `Influencer/Top Model`,
    content_line_one: `pretend to be posing for a photograph and strike 10 different poses.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec8',
    title: `Rewind`,
    content_line_one: `say your full name backwards without a pause.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec9',
    title: `Casanova`,
    content_line_one: `tell everyone how many sex partners you've had`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec10',
    content_line_one: `Accento`,
    content: `describe your toilet technique with an Italian accent.`,
    comment: `Capeesh?`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec11',
    title: `Top Secret`,
    content_line_one: `reveal one thing you’ve never told anyone.`,
    comment: `Get it off your chest.`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec12',
    title: `Cheeky Pointer`,
    content_line_one: `point to the most and the least annoying people in the room. Don’t say which one’s which.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec13',
    title: `Drunk Tat`,
    content_line_one: `Get a marker and choose one co-player to give you a matching tattoo.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec14',
    title: `Soggy Slap`,
    content_line_one: `hold a mouthful of water and slap each other with a tortilla (or something similar) until you burst.`,
    comment: `Hold the drool.`,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec15',
    title: `Mall Mannequin`,
    content_line_one: `get moved by other players and stand still in that position. Get your photos taken.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec16',
    title: `Catwalk`,
    content_line_one: `do a catwalk as if you’re the top model at a fashion show.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec17',
    title: `Mad Architect`,
    content_line_one: `get 5 different items and stack them up in 15 seconds.`,
    comment: ``,
    timer: 15,
    cardColor: 'lemonadeScore',
  },
  {
    id: 'lec18',
    title: `Loo Swag`,
    content_line_one: `get some toilet paper and make yourself a scarf to wear for the rest of the game.`,
    comment: ``,
    timer: false,
    cardColor: 'lemonadeScore',
  },
];
