export const martiniCardData = [
  {
    id: 'mac1',
    title: `Sleep Talk`,
    content_line_one: 'Lay down on the ground and ',
    content_line_two:
      ' as you pretend to be asleep. You do this every night regardless.',
    comment: `You do this every night regardless.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac2',
    title: `Grenade Serenade`,
    content_line_one: 'Gaze at the player to your right and ',
    content_line_two: ' as if you’re trying to flirt.',
    comment: `Don’t try this in public.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac3',
    title: `Double Stacked`,
    content_line_one: 'Choose a player and ',
    content_line_two: ' as you sit on their lap.',
    comment: `Just embrace the awkwardness.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac4',
    title: `Piggy Ride`,
    content_line_one: 'Give a quick piggy back-ride to one of the players and ',
    content_line_two: ' as you carry them around.',
    comment: `Always carrying the team.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac5',
    title: `Sweaty palms`,
    content_line_one: 'Choose two players and ',
    content_line_two: ' as you hold their hands.',
    comment: `You won’t need them now anyway.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac6',
    title: `Gorilla Grip`,
    content_line_one: 'Arm-wrestle every player in the room and ',
    content_line_two: ' for each defeat.',
    comment: `Do you even lift?`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac7',
    title: `Flamingo`,
    content_line_one: 'Stand on one leg and ',
    content_line_two: '.',
    comment: `It’s just you vs gravity.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac8',
    title: `Limboo!`,
    content_line_one: 'Everyone play limbo. The first player to stumble must ',
    content_line_two: ' after everyone is finished.',
    comment: `Don't forget the music!`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac9',
    title: `Kitchen Master`,
    content_line_one:
      'Throw a small piece of food in the air and catch it using a spoon. ',
    content_line_two: ' after you catch it without dropping the piece.',
    comment: `Don’t say it’s the shaky hands again.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac10',
    title: `Rock-Paper-Scissors`,
    content_line_one: 'Play ‘Rock-Paper-Scissors’ with every player and ',
    content_line_two: ' every time you get wrecked.',
    comment: `On the Rocks`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac11',
    title: `Heads & Tails`,
    content_line_one: 'Get a coin and toss it. If it lands on heads ',
    content_line_two:
      ' alone, if it lands on tails pick someone to do it with you.',
    comment: `Feeling lucky today?`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac12',
    title: `Free Kick`,
    content_line_one:
      'Flick a small paper ball through a goalpost made by the player sitting across and ',
    content_line_two: ' every time you miss.',
    comment: `It’s football, not football.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac13',
    title: `On the Mat`,
    content_line_one: 'Exit the room and ',
    content_line_two: ' behind the door.',
    comment: `Hope no one locks you out.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac14',
    title: `Heads or Tails`,
    content_line_one: 'Get a coin and toss it. If it lands on heads ',
    content_line_two:
      ' alone, if it lands on tails pick someone to do it with you.',
    comment: `Feeling lucky today?`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac15',
    title: `Free Kick`,
    content_line_one:
      'Flick a small paper ball through a goalpost made by the player sitting across and ',
    content_line_two: ' every time you miss.',
    comment: `It’s football, not football.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac16',
    title: `Tic-Tac-Toe`,
    content_line_one: 'Play Tic-Tac-Toe with a player to your right and ',
    content_line_two: ' if you end up in a tie or lose.',
    comment: `Xs and Os don’t land on your nose.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac17',
    title: `Broken Telephone`,
    content_line_one:
      'Whisper a two-sentance story to a player on your left and they must do the same until it comes back to you. ',
    content_line_two: ' if the story changed.',
    comment: `Chinese whispers are dangerous.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac18',
    title: `Turn-Off`,
    content_line_one: 'Get into your favourite sex position and ',
    content_line_two: '.',
    comment: `That is your mission(ary).`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac19',
    title: `Knee Pang`,
    content_line_one:
      'Get on one knee in front of the player to your right and ',
    content_line_two: '.',
    comment: `Don't worry, they arn't proposing.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac20',
    title: `Back Crack`,
    content_line_one: 'Stand up and ',
    content_line_two: ' as you arch back and touch the ground with your palms.',
    comment: `Without breaking your back.`,
    cardColor: 'martiniScore',
  },
];
