export const martiniCardData = [
  // {
  //   id: 'mac1',
  //   title: `Sleep Talk`,
  //   content_line_one: 'lay down on the ground and ',
  //   content_line_two: ' as you pretend to be asleep.',
  //   comment: `You do this every night regardless.`,
  //   cardColor: 'martiniScore',
  // },
  {
    id: 'mac2',
    title: `Grenade Serenade`,
    content_line_one: 'look at the player to your right and ',
    content_line_two: ' as if you’re trying to flirt.',
    comment: `Don’t try this in public.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac3',
    title: `Double Stacked`,
    content_line_one: 'choose a player and ',
    content_line_two: ' as you sit on their lap.',
    comment: `Just embrace the awkwardness.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac4',
    title: `Sweaty palms`,
    content_line_one: 'choose two players and ',
    content_line_two: ' as you hold their hands.',
    comment: `Don't be shy.`,
    cardColor: 'martiniScore',
  },
  // {
  //   id: 'mac5',
  //   title: `Dead Arm`,
  //   content_line_one: 'Arm-wrestle every player in the room and ',
  //   content_line_two: ' for each defeat.',
  //   comment: `Show them how it's done.`,
  //   cardColor: 'martiniScore',
  // },
  {
    id: 'mac6',
    title: `Wonky Ass`,
    content_line_one: '',
    content_line_two: ' as you stand on one leg.',
    comment: `Keep it cool.`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac7',
    title: `Down The Hatch`,
    content_line_one: '',
    content_line_two:
      ' as you catch a small piece of food after tossing it in the air.',
    comment: `Drop the 5 second rule.`,
    cardColor: 'martiniScore',
  },
  // {
  //   id: 'mac8',
  //   title: `Rock-Paper-Scissors`,
  //   content_line_one:
  //     'play ‘Rock-Paper-Scissors’ with each one of your co-players and ',
  //   content_line_two: ' every time you lose.',
  //   comment: `Beat the odds.`,
  //   cardColor: 'martiniScore',
  // },
  {
    id: 'mac9',
    title: `Piggy-Back`,
    content_line_one: 'give a quick piggy-back-ride to one of the players and ',
    content_line_two: ' as you carry them around. Lap the room to win.',
    comment: `Always carrying the team.`,
    cardColor: 'martiniScore',
  },
  // {
  //   id: 'mac10',
  //   title: `Heads & Tails`,
  //   content_line_one: 'get a coin and toss it. If it lands on heads ',
  //   content_line_two:
  //     ' alone, if it lands on tails pick someone to do it with you.',
  //   comment: `Feeling lucky today?`,
  //   cardColor: 'martiniScore',
  // },
  // {
  //   id: 'mac11',
  //   title: `Free Kick`,
  //   content_line_one:
  //     'flick a small paper ball through a goalpost made by the player sitting across and ',
  //   content_line_two: ' every time you miss.',
  //   comment: `It’s football, not football.`,
  //   cardColor: 'martiniScore',
  // },
  {
    id: 'mac12',
    title: `Locked Out`,
    content_line_one: 'exit the room and ',
    content_line_two: ' behind the door.',
    comment: `Hope no one locks you out.`,
    cardColor: 'martiniScore',
  },
  // {
  //   id: 'mac13',
  //   title: `Tic-Tac-Toe`,
  //   content_line_one: 'play Tic-Tac-Toe with a player to your right and ',
  //   content_line_two: ' if you end up in a tie or get wrecked.',
  //   comment: ``,
  //   cardColor: 'martiniScore',
  // },
  {
    id: 'mac14',
    title: `Chinese Whispers`,
    content_line_one:
      'chinese whisper a description of your mum going clockwise and ',
    content_line_two: ' if the whisper is not intact.',
    comment: `No hard feelings?`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac15',
    title: `Sleep Walk`,
    content_line_one: 'close your eyes and ',
    content_line_two: ' as you walk around the table.',
    comment: `No peeking.`,
    cardColor: 'martiniScore',
  },
  // {
  //   id: 'mac16',
  //   title: `Moon Landing`,
  //   content_line_one: 'put a bowl over your head and ',
  //   content_line_two: ' as you act out the moon landing.',
  //   comment: `It’s one small step for you, and an even smaller one for mankind.`,
  //   cardColor: 'martiniScore',
  // },
  // {
  //   id: 'mac17',
  //   title: `Turn-Off`,
  //   content_line_one: 'get into your favourite sex position and ',
  //   content_line_two: '.',
  //   comment: `That is your mission(ary).`,
  //   cardColor: 'martiniScore',
  // },
  {
    id: 'mac18',
    title: `Limpy Simp`,
    content_line_one: 'kneel in front of the player to your right and ',
    content_line_two: '.',
    comment: `Keep it short`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac19',
    title: `The Crab`,
    content_line_one: '',
    content_line_two: ' as you arch back and touch the ground with your palms.',
    comment: `You've got crabs!`,
    cardColor: 'martiniScore',
  },
  {
    id: 'mac20',
    title: `Time-Out`,
    content_line_one: 'sit in a corner of the room facing the wall and ',
    content_line_two: '',
    comment: ``,
    cardColor: 'martiniScore',
  },
];
