export const mojitoCardData = [
  {
    id: 'moc1',
    title: `No Vain No Gain`,
    content_line_one: `do 20 squats and compliment yourself.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc2',
    title: `Treasure Hunt`,
    content_line_one: `leave the room. Everyone else must hide your drink somewhere. Find it in 30 seconds or drink!`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc3',
    title: `Top Swap`,
    content_line_one: `choose a player to swap your top with.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc4',
    title: `Head Over Heels`,
    content_line_one: `do a handstand.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc5',
    title: `Tier List`,
    content_line_one: `rank every player from the most to the least favourite.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc6',
    title: `Hot or Not`,
    content_line_one: `rank every player from the prettiest to the least pretty.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc7',
    title: `No Filter`,
    content_line_one: `admit one thing you don't like about each player.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc8',
    title: `Screen Protector`,
    content_line_one: `spin around 10 times and throw your phone at a player you trust catching it.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc9',
    title: `Brain Freeze`,
    content_line_one: `pick one thing from the freezer and hold it in your mouth for 30 seconds.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc10',
    title: `Flat Back`,
    content_line_one: `do 10 push-ups and balance a random item on your back. Let your co-players decide what the item is.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc11',
    title: `Honest Lies`,
    content_line_one: `tell two truths and a lie. Others make a collective guess which statement was a lie.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc12',
    title: `MC Woozy`,
    content_line_one: `Rhyme 10 different words in a row in 15 seconds.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc13',
    title: `Mime On Time`,
    content_line_one: `imitate one of the players and have the group guess who it is in 30 seconds, you win if they guess.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc14',
    title: `Frisk No Risk`,
    content_line_one: `search each player as if you’re the gate security and they’re at the airport.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc15',
    title: `No-Panty`,
    content_line_one: `leave the room and come back with your undies in hand.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc15',
    title: `Sauced Up`,
    content_line_one: `get some ketchup and make yourself a refreshing facemask.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc16',
    title: `Wet Head`,
    content_line_one: `wash your hair in a sink. That’s one way to cool down.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc17',
    title: `Party Flavour`,
    content_line_one: `lick every corner of the table.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc18',
    title: `Hoochy Smooch`,
    content_line_one: `choose a player to kiss.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc19',
    title: `Fuck, Marry, Kill`,
    content_line_one: `pick out the players you would Fuck, Marry, Kill.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
];
