export const mojitoCard = () => {
	const mojitoCards = [
		{
			id: 'moc1',
			title: `No Vain No Gain`,
			content: `do 20 squats and compliment yourself.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc2',
			title: `Treasure Hunt`,
			content: `leave the room. Everyone else must hide your drink somewhere. Find it in 30 seconds or drink!`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc3',
			title: `Top Swap`,
			content: `choose a player to swap your top with.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc4',
			title: `Head Over Heels`,
			content: `do a handstand.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc5',
			title: `Tier List`,
			content: `rank every player from the most to the least favourite.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc6',
			title: `Hot or Not`,
			content: `rank every player from the prettiest to the least pretty.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc7',
			title: `No Filter`,
			content: `admit one thing you don't like about each player.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc8',
			title: `Screen Protector`,
			content: `spin around 10 times and throw your phone at a player you trust catching it.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc9',
			title: `Brain Freeze`,
			content: `pick one thing from the freezer and hold it in your mouth for 30 seconds.`,
			comment: ``,
			timer: 30,
		},
		{
			id: 'moc10',
			title: `Flat Back`,
			content: `do 10 push-ups and balance a random item on your back. Let your co-players decide what the item is.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc11',
			title: `Honest Lies`,
			content: `tell two truths and a lie. Others make a collective guess which statement was a lie.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc12',
			title: `MC Woozy`,
			content: `Rhyme 10 different words in a row in 15 seconds.`,
			comment: ``,
			timer: 15,
		},
		{
			id: 'moc13',
			title: `Mime On Time`,
			content: `imitate one of the players and have the group guess who it is in 30 seconds, you win if they guess.`,
			comment: ``,
			timer: 30,
		},
		{
			id: 'moc14',
			title: `Frisk No Risk`,
			content: `search each player as if you’re the gate security and they’re at the airport.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc15',
			title: `No-Panty`,
			content: `leave the room and come back with your undies in hand.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc15',
			title: `Sauced Up`,
			content: `get some ketchup and make yourself a refreshing facemask.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc16',
			title: `Wet Head`,
			content: `wash your hair in a sink. That’s one way to cool down.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc17',
			title: `Party Flavour`,
			content: `lick every corner of the table.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc18',
			title: `Hoochy Smooch`,
			content: `choose a player to kiss.`,
			comment: ``,
			timer: false,
		},
		{
			id: 'moc19',
			title: `Fuck, Marry, Kill`,
			content: `pick out the players you would Fuck, Marry, Kill.`,
			comment: ``,
			timer: false,
		},
	];
	const randomWordIndex = Math.floor(Math.random() * mojitoCards.length) + 0;
	const challenge = mojitoCards[randomWordIndex];
	return challenge;
};

// `Spin the arrow and take a shot with a person that it ends up pointing at.`,
//     `Take a shot.`,
//     `Ask a person to your left "When is my birthday?". If they get it right - you drink, if they get it wrong - they drink.`,
//     `Hide and Seeeek! Cover your eyes and ears. Everyone else: hide! The first one found - take 2 shots, the second one found - take 1 shot.`,
//     `Swap a piece of clothing with a player to your right.`,
//     `Swap a piece of clothing with a player to your left.`,
//     `Do a handstand.`,
//     `Rank every player from your most favourite to the least favourite.`,
//     `Rank every player from the prettiest to the least pretty.`,
//     `Admit one thing you don't like about each player.`,
//     `Tell everyone 3 things you don't like about yourself.`,
//     `Pick a player to swap your next dare with at some point during the game.`,
//     `Give a high-five to every player that makes you smile until your next turn.`,
//     `Trust one other player to spin around 10 times and then throw your phone at them to catch.`,
//     `Spin the arrow. The player that it lands on has to pick one thing from the freezer. Hold that in your mouth for 5 minutes.`,
//     `Do 10 push-ups and let other players put one random item on your back. (Drink if you drop it).`,
//     `Pick one player and pour a random shot of alcohol into their drink without them noticing, you have 15 minutes. (Finish that drink if the player notices).`,
//     `Make other players laugh. If at least one player cracks a smile - they all drink, if not - you drink. (You have 2 minutes).`,
//     `Tell two truths and a lie. Others make a collective guess which statement was a lie.`,
//     `Everyone must make you laugh in 1 minute. They all drink if they fail or you drink if you don’t crack up.`,
