export const mojitoCardData = [
  {
    id: 'moc1',
    title: `No Vain No Gain`,
    content_line_one: `do 20 squats and compliment yourself.`,
    comment: `Ain't got squat to say?`,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc2',
    title: `Top Swap`,
    content_line_one: `choose a player to swap your top with.`,
    comment: `Thrifty.`,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc3',
    title: `Head Over Heels`,
    content_line_one: `do a handstand.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc4',
    title: `Screen Protector`,
    content_line_one: `spin around 10 times and throw your phone to a player you trust catching it.`,
    comment: `Time for a new contract.`,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc5',
    title: `Brain Freeze`,
    content_line_one: `get one thing from the freezer and hold it in your undies for 30 seconds.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc6',
    title: `Flat Back`,
    content_line_one: `do 10 push-ups and balance one random item on your back. Let your co-players decide what is that extra weight.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc7',
    title: `Frisk No Risk`,
    content_line_one: `search each player as if you’re the gate security and they’re at the airport.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc8',
    title: `MC Woozy`,
    content_line_one: `rhyme 10 words in a row without a single pause.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc9',
    title: `No-Panty`,
    content_line_one: `leave the room and come back with your undies in hand.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc10',
    title: `Sauced Up`,
    content_line_one: `get some ketchup and make yourself a refreshing facemask.`,
    comment: `Maybe you'll ketchup up on points.`,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc11',
    title: `Wet Head`,
    content_line_one: `wash your hair in a sink.`,
    comment: `Let that sink in.`,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc12',
    title: `Party Flavour`,
    content_line_one: `lick all 4 corners of a table.`,
    comment: `Right around the corner.`,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc13',
    title: `Influencer/Top Model`,
    content_line_one: `pretend to be posing for a photograph and strike 10 different poses.`,
    comment: `Insta worthy.`,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc14',
    title: `Rewind`,
    content_line_one: `say your full name backwards without a pause.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc15',
    title: `No-Panty`,
    content_line_one: `leave the room and come back with your undies in hand.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc15',
    title: `Drunk Tat`,
    content_line_one: `get a marker and let one of the players do a small face tattoo for you.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
  {
    id: 'moc16',
    title: `Loo Swag`,
    content_line_one: `get some toilet paper and make yourself a scarf to wear for the rest of the game.`,
    comment: ``,
    cardColor: 'mojitoScore',
  },
];
