export const whiskeyCardData = [
  {
    id: 'whc1',
    title: `Class Clown`,
    content_line_one: ``,
    content_line_two: 'and make at least one player laugh.',
    comment: `Easy-peasy, right?`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc2',
    title: `Poker Face`,
    content_line_one: `keep a poker face and `,
    content_line_two: '.',
    comment: `Just like you practised.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc3',
    title: `M.C. Hammer`,
    content_line_one: ``,
    content_line_two: ` as you say "Can't touch this".`,
    comment: `Stop, Hammer time.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc4',
    title: `Flash Back`,
    content_line_one: `get your hands tied up behind your back and `,
    content_line_two: '.',
    comment: `Don't act like it's your first time.`,
    cardColor: 'whiskeyScore',
  },
  // {
  //   id: 'whc5',
  //   title: `Sniper`,
  //   content_line_one: `place a cup at the opposite end of the table and try to throw a small item into it. `,
  //   content_line_two: ' after each shot until you make it.',
  //   comment: `Thought those ‘Beer Pong’ nights won’t ever pay off?`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc6',
  //   title: `Chicken Legs`,
  //   content_line_one: `crouch-walk around the room and `,
  //   content_line_two: ' in each corner.',
  //   comment: `For all the leg days you skipped.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc7',
  //   title: `Mama's boy`,
  //   content_line_one: ``,
  //   content_line_two: ' and shout mom for help.',
  //   comment: `Unfortunately, it's all on you now.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc8',
  //   title: `Patriot`,
  //   content_line_one: ``,
  //   content_line_two: ' and sing your National anthem as loud as you can.',
  //   comment: `You know how it goes.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc9',
  //   title: `Soaked`,
  //   content_line_one: ``,
  //   content_line_two: ' and down a glass of water',
  //   comment: `Stay hydrated.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc10',
  //   title: `Minute of Silence`,
  //   content_line_one: ``,
  //   content_line_two: ' and do a 360° without making a sound.',
  //   comment: `Keep it down.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc11',
  //   title: `Snack Time`,
  //   content_line_one: ``,
  //   content_line_two:
  //     ' and try to land a piece of food in your mouth as the player across throws it.',
  //   comment: `Just without making a total mess around, right?`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc11',
  //   title: `Elevator Pitch`,
  //   content_line_one: `describe your love for “Topped Off” and `,
  //   content_line_two: ' as you’re doing so.',
  //   comment: `Make a demo they won’t forget.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc13',
  //   title: `Macarena`,
  //   content_line_one: `do the macarena until the song ends and `,
  //   content_line_two: ' after every “Ayyyy Macarena!”.',
  //   comment: `You love this song, don’t you?`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc14',
  //   title: `Sunday Roast`,
  //   content_line_one: ``,
  //   content_line_two: ` and roast other players.`,
  //   comment: `Don't be rude.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc15',
  //   title: `Naked Truth`,
  //   content_line_one: ``,
  //   content_line_two: ' as you reveal a fun fact about yourself.',
  //   comment: `Spill the beans.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc16',
  //   title: `Stuntman`,
  //   content_line_one: `do a cartwheel and `,
  //   content_line_two: ' as soon as you land.',
  //   comment: `No one’s a natural.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc17',
  //   title: `Shot in the dark`,
  //   content_line_one: `close your eyes and describe everyone’s eye color. Also, `,
  //   content_line_two: ` each time you get it wrong.`,
  //   comment: `Trust your gut… or memory.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc18',
  //   title: `Thumb War`,
  //   content_line_one: `challenge each player to a thumb war and `,
  //   content_line_two: ' every time you lose.',
  //   comment: `One thumb to rule them all.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc19',
  //   title: `Plot Twist`,
  //   content_line_one: `choose a topic and let the group build a sentence word by word. Repeat the exact sentence and `,
  //   content_line_two: '.',
  //   comment: `Shoot your shot or take a shot.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc20',
  //   title: `Spooning`,
  //   content_line_one: `flip a spoon into a glass and `,
  //   content_line_two: ' every time you miss.',
  //   comment: `Little spoon or big spoon, doesn’t matter this time.`,
  //   cardColor: 'whiskeyScore',
  // },
];

export const whiskeyCardDataCopy = [
  {
    id: 'whc1',
    title: `Class Clown`,
    content_line_one: ``,
    content_line_two: 'and make at least one player laugh.',
    comment: `Easy-peasy, right?`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc2',
    title: `Poker Face`,
    content_line_one: `keep a poker face and `,
    content_line_two: '.',
    comment: `Just like you practised.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc3',
    title: `M.C. Hammer`,
    content_line_one: ``,
    content_line_two: ` as you say "Can't touch this".`,
    comment: `Stop, Hammer time.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc4',
    title: `Flash Back`,
    content_line_one: `get your hands tied up behind your back and `,
    content_line_two: '.',
    comment: `Don't act like it's your first time.`,
    cardColor: 'whiskeyScore',
  },
  // {
  //   id: 'whc5',
  //   title: `Sniper`,
  //   content_line_one: `place a cup at the opposite end of the table and try to throw a small item into it. `,
  //   content_line_two: ' after each shot until you make it.',
  //   comment: `Thought those ‘Beer Pong’ nights won’t ever pay off?`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc6',
  //   title: `Chicken Legs`,
  //   content_line_one: `crouch-walk around the room and `,
  //   content_line_two: ' in each corner.',
  //   comment: `For all the leg days you skipped.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc7',
  //   title: `Mama's boy`,
  //   content_line_one: ``,
  //   content_line_two: ' and shout mom for help.',
  //   comment: `Unfortunately, it's all on you now.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc8',
  //   title: `Patriot`,
  //   content_line_one: ``,
  //   content_line_two: ' and sing your National anthem as loud as you can.',
  //   comment: `You know how it goes.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc9',
  //   title: `Soaked`,
  //   content_line_one: ``,
  //   content_line_two: ' and down a glass of water',
  //   comment: `Stay hydrated.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc10',
  //   title: `Minute of Silence`,
  //   content_line_one: ``,
  //   content_line_two: ' and do a 360° without making a sound.',
  //   comment: `Keep it down.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc11',
  //   title: `Snack Time`,
  //   content_line_one: ``,
  //   content_line_two:
  //     ' and try to land a piece of food in your mouth as the player across throws it.',
  //   comment: `Just without making a total mess around, right?`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc11',
  //   title: `Elevator Pitch`,
  //   content_line_one: `describe your love for “Topped Off” and `,
  //   content_line_two: ' as you’re doing so.',
  //   comment: `Make a demo they won’t forget.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc13',
  //   title: `Macarena`,
  //   content_line_one: `do the macarena until the song ends and `,
  //   content_line_two: ' after every “Ayyyy Macarena!”.',
  //   comment: `You love this song, don’t you?`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc14',
  //   title: `Sunday Roast`,
  //   content_line_one: ``,
  //   content_line_two: ` and roast other players.`,
  //   comment: `Don't be rude.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc15',
  //   title: `Naked Truth`,
  //   content_line_one: ``,
  //   content_line_two: ' as you reveal a fun fact about yourself.',
  //   comment: `Spill the beans.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc16',
  //   title: `Stuntman`,
  //   content_line_one: `do a cartwheel and `,
  //   content_line_two: ' as soon as you land.',
  //   comment: `No one’s a natural.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc17',
  //   title: `Shot in the dark`,
  //   content_line_one: `close your eyes and describe everyone’s eye color. Also, `,
  //   content_line_two: ` each time you get it wrong.`,
  //   comment: `Trust your gut… or memory.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc18',
  //   title: `Thumb War`,
  //   content_line_one: `challenge each player to a thumb war and `,
  //   content_line_two: ' every time you lose.',
  //   comment: `One thumb to rule them all.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc19',
  //   title: `Plot Twist`,
  //   content_line_one: `choose a topic and let the group build a sentence word by word. Repeat the exact sentence and `,
  //   content_line_two: '.',
  //   comment: `Shoot your shot or take a shot.`,
  //   cardColor: 'whiskeyScore',
  // },
  // {
  //   id: 'whc20',
  //   title: `Spooning`,
  //   content_line_one: `flip a spoon into a glass and `,
  //   content_line_two: ' every time you miss.',
  //   comment: `Little spoon or big spoon, doesn’t matter this time.`,
  //   cardColor: 'whiskeyScore',
  // },
];
