export const whiskeyCardData = [
  {
    id: 'whc1',
    title: `Class Clown`,
    content_line_one: ``,
    content_line_two: 'and make at least one player laugh.',
    comment: `Easy, right?`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc2',
    title: `Poker Face`,
    content_line_one: `Keep a poker face and `,
    content_line_two: '.',
    comment: `Let’s hope all the flies on the wall stay silent.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc3',
    title: `Shit Show`,
    content_line_one: ``,
    content_line_two:
      ' as if it’s a part of your stand-up because every player you crack up takes a drink.',
    comment: `Hope no one’s filming`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc4',
    title: `Flash Back`,
    content_line_one: `Get your hands tied up behind your back and `,
    content_line_two: '.',
    comment: `Don't act like it's your first time.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc5',
    title: `Sniper`,
    content_line_one: `Place a cup at the opposite end of the table and try to throw a small item into it. `,
    content_line_two: ' after each shot until you make it.',
    comment: `Thought those ‘Beer Pong’ nights won’t ever pay off?`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc6',
    title: `Chicken Legs`,
    content_line_one: `Crouch-walk around the room and `,
    content_line_two: ' in each corner.',
    comment: `For all the leg days you skipped.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc7',
    title: `Ready Steady`,
    content_line_one: `Keep one leg off the ground and `,
    content_line_two: '.',
    comment: `There’s no way you took too much to mess this up.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc8',
    title: `Patriot`,
    content_line_one: ``,
    content_line_two: ' and sing your National anthem as loud as you can.',
    comment: `You know the words right?`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc9',
    title: `Soaked`,
    content_line_one: ``,
    content_line_two: ' and take a shot/sip of your drink.',
    comment: `Stay hydrated.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc10',
    title: `Minute of Silence`,
    content_line_one: ``,
    content_line_two: ' and do a 360° without making a sound.',
    comment: `Keep it down.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc11',
    title: `Snack Time`,
    content_line_one: ``,
    content_line_two:
      ' and try to land a piece of food in your mouth as the player across throws it.',
    comment: `Just without making a total mess around, right?`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc11',
    title: `Elevator Pitch`,
    content_line_one: `Convince other players to buy “Topped Off” and `,
    content_line_two: ' as you’re doing so.',
    comment: `Make a demo they won’t forget.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc13',
    title: `Macarena`,
    content_line_one: `Do the macarena until the song ends and `,
    content_line_two: ' after every “Ayyyy Macarena!”.',
    comment: `You love this song, don’t you?`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc14',
    title: `Bar Special`,
    content_line_one: `Choose a player to make you a funky cocktail. `,
    content_line_two: ` as you're drinking it.`,
    comment: `Bottoms up!`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc15',
    title: `Back to School`,
    content_line_one: `Give every player a nickname. `,
    content_line_two: ' after you drop one.',
    comment: `Go easy on them ok?`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc16',
    title: `Stuntman`,
    content_line_one: `Do a cartwheel and `,
    content_line_two: ' as soon as you land.',
    comment: `No one’s a natural.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc17',
    title: `Shot in the dark`,
    content_line_one: `Close your eyes and describe everyone’s eye color. `,
    content_line_two: ` each time you get it wrong.`,
    comment: `Trust your gut… or memory.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc18',
    title: `Thumb War`,
    content_line_one: `Challenge each player to a thumb war and `,
    content_line_two: ' each time you lose.',
    comment: `One thumb to rule them all.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc19',
    title: `Plot Twist`,
    content_line_one: `Choose a topic and let the group build a sentence word by word. `,
    content_line_two: ' and repeat the exact sentence.',
    comment: `Shoot your shot or take a shot.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc20',
    title: `Flip Off/Front Flip/Hardflip`,
    content_line_one: `Flip a spoon into a glass and `,
    content_line_two: ' everytime you miss.',
    comment: `Little spoon or big spoon, doesn’t matter this time.`,
    cardColor: 'whiskeyScore',
  },
  {
    id: 'whc21',
    title: `Bottle Flip`,
    content_line_one: `play bottle flip and `,
    content_line_two: ' every time you fail the landing until you succeed.',
    comment: `You’ve done this before.`,
    cardColor: 'whiskeyScore',
  },
];
